server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrierdb
    username: prasannakrishnabhagwat
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: carrierdb
  flyway:
    enabled: true
    schemas: carrierdb
    default-schema: carrierdb
    locations: classpath:db/migration
    validate-on-migrate: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: carrier-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  data:
    mongodb:
      uri: mongodb://localhost:27017/carrierdb

multitenancy:
  enabled: true
  default-tenant-id: carrierdb
  fail-on-missing-tenant: false

api:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: carrier-service
      auto-offset-reset: earliest

service:
  core:
    rest-client:
      response-time-out: 5000
      connection-time-out: 3000
    api-configs:
      contract-search:
        host: http://localhost:8089
        path: /api/contracts/search
        method: GET

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  config: classpath:logback-observability.xml
