spring:
  application:
    name: storeService
  datasource:
    url: 'jdbc:postgresql://localhost:5432/storedb'
    username: prasannakrishnabhagwat
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 'localhost:9092'
    producer:
      bootstrap-servers: 'localhost:9092'
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: 'localhost:9092'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: store-service-group
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
server:
  port: 8092
app:
  kafka:
    topics:
      store-events:
        name: store.events
        partitions: 6
        replicas: 3
        retention-ms: 604800000
        cleanup-policy: delete
