spring.application.name=userService
server.port = 8087
# Database connection properties
# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://ep-bold-star-a1jq9u4k-pooler.ap-southeast-1.aws.neon.tech/neondb?currentSchema=userdb&sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6Fn5yTvISaoH
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=userdb

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/userdb
spring.data.mongodb.auto-index-creation=true

# Kafka
kafka.bootstrap-servers=localhost:9092
kafka.topic=user-events

# Kafka Broker Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Consumer Configuration (needed for your Kafka listeners)
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=user-mongo-updater-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# --- Topic Configuration ---
app.kafka.topics.user-events.name=user.events
app.kafka.topics.org-events.name=org.events
#debug=true
